# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          s4ng
baseurl:        ""
url:            "http://s4ng.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         s4ng
  url:          http://s4ng.github.io/
  email:        zalcls951201@gmail.com  
  github:       s4ng
  twitter:      

# Custom vars
version:        3.4.2
github:
  repo:         https://github.com/s4ng/s4ng.github.io