// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The docs sidebar is autogenerated from the folder structure under docs/.
 * To change the hierarchy, move folders and edit each folder's _category_.json
 * — no manual sidebar editing required.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
